<a href="https://colab.research.google.com/github/amirrexad/First-Deep-Learning-Projects/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import torch
torch.cuda.is_available()

True

In [35]:
device = "cpu"
if torch.cuda.is_available(): device = "cuda"

print(device)

cuda


Define the ANN class

In [36]:
from torch import nn

class Network(nn.Module):
  def __init__(self, v, w):
    super().__init__()
    self.n = v
    self.m = w
  def forward(self, x, y):
    if x > y:
      return self.n
    else:
      return self.m

model = Network(7, 8)
model(5, 6)




8

In [37]:
x = [[8,1,10,1,3],
     [18,0,2,0,0],
     [2,0,20,0,0],
     [10,1,6,0,1],
     [20,1,7,1,1],
     [15,1,9,0,0],
     [30,0,5,1,1],
     [4,0,10,1,1],
     [24,0,15,0,2],
     [4,1,15,1,5],
     [40,0,1,0,0]]

y = [[15.6],[18.5],[13.5],[13.6],[16],[14.35],[12],[18.9],[17],[17.4],[16]]


In [38]:
class ANN(nn.Module):
  def __init__(self):
    super().__init__()
    self.layers = nn.Sequential(
        nn.Linear(5,8),
        nn.ReLU(),
        nn.Linear(8,4),
        nn.ReLU(),
        nn.Linear(4,1)
    )
  def forward(self, x):
    return self.layers(x)

In [39]:
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

x.shape


torch.Size([11, 5])

In [40]:
model = ANN()
model(x)

tensor([[ 0.2476],
        [ 0.1765],
        [ 0.0373],
        [ 0.2872],
        [ 0.3478],
        [ 0.3453],
        [ 0.1242],
        [ 0.2256],
        [ 0.3583],
        [ 0.1832],
        [-0.1230]], grad_fn=<AddmmBackward0>)

Loss func & Optimizer

In [41]:
for i in test.parameters():
  print(i)
  print("-"*10)

Parameter containing:
tensor([[ 0.3670, -0.2153,  0.1752, -0.4171, -0.4138],
        [-0.1450, -0.3695,  0.2509, -0.3077,  0.3961],
        [ 0.0643,  0.1908, -0.2193,  0.2705,  0.3434]], requires_grad=True)
----------
Parameter containing:
tensor([ 0.2577,  0.1578, -0.2068], requires_grad=True)
----------
Parameter containing:
tensor([[-0.0690,  0.3680, -0.4967]], requires_grad=True)
----------
Parameter containing:
tensor([-0.3725], requires_grad=True)
----------


In [44]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

Training loops

In [49]:
epoch = 5000
for i in range(epoch):
  # step 1: Reset grad
  ## reset the whole 89 w & b:
  optimizer.zero_grad()

  # step 2: Feed-forward
  y_hat = model(x)

  # step 3: Compute the loss
  loss = criterion(y_hat, y)

  # step 4: Backpropagation
  loss.backward()

  # step 5: Update parameters (w & b)
  optimizer.step()

  if i%50==0:
    print(f"epoch: {i} / loss: {loss.item()}")


epoch: 0 / loss: 15.813307762145996
epoch: 50 / loss: 15.490616798400879
epoch: 100 / loss: 15.159612655639648
epoch: 150 / loss: 14.81875228881836
epoch: 200 / loss: 14.470635414123535
epoch: 250 / loss: 14.115670204162598
epoch: 300 / loss: 13.757454872131348
epoch: 350 / loss: 13.39914321899414
epoch: 400 / loss: 13.04504680633545
epoch: 450 / loss: 12.695903778076172
epoch: 500 / loss: 12.351058959960938
epoch: 550 / loss: 12.00858211517334
epoch: 600 / loss: 11.665289878845215
epoch: 650 / loss: 11.312309265136719
epoch: 700 / loss: 10.94564151763916
epoch: 750 / loss: 10.565115928649902
epoch: 800 / loss: 10.170241355895996
epoch: 850 / loss: 9.761980056762695
epoch: 900 / loss: 9.335272789001465
epoch: 950 / loss: 8.77145767211914
epoch: 1000 / loss: 8.13433837890625
epoch: 1050 / loss: 7.419848442077637
epoch: 1100 / loss: 6.698198318481445
epoch: 1150 / loss: 5.9546895027160645
epoch: 1200 / loss: 5.139286994934082
epoch: 1250 / loss: 4.357664108276367
epoch: 1300 / loss: 3.65

In [50]:
model(x)

tensor([[15.6000],
        [18.5000],
        [13.5000],
        [13.6000],
        [16.0000],
        [14.3500],
        [12.0000],
        [18.9000],
        [17.0000],
        [17.4000],
        [16.0000]], grad_fn=<AddmmBackward0>)

Inference

In [51]:
model.eval()

ANN(
  (layers): Sequential(
    (0): Linear(in_features=5, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=4, bias=True)
    (3): ReLU()
    (4): Linear(in_features=4, out_features=1, bias=True)
  )
)

In [53]:
x_test = [[12,1,0,0,2],[5,1,1,1,0]]
x_test = torch.tensor(x_test, dtype = torch.float32)

In [54]:
model(x_test)

tensor([[16.0707],
        [19.4290]], grad_fn=<AddmmBackward0>)